### ISSUE TITLE
学习github的actions自动发布

### ISSUE THREAD

**Issue by XJQ124** [XJQ124/-#1]

**Comment by XJQ124** [comment]
- #### 任务：1、使用github上的action进行持续集成，进行自动发布。
- #### 2、学习安卓Navigation（导航）的基础知识

### 持续集成
  github链接： [https://github.com/XJQ124/MusicPlayer](url)
1、上周五我是了解了他的一个大概，官方的文档对这个功能进行了介绍
文档链接：[https://docs.github.com/zh/actions/quickstart](url)

2、周末抽空试了试，我最开始不知道如何下手，然后在本地完成了apk的打包。这里有一个坑，我不知道安卓的apk是需要签名的，所以此时的这个包其实是不能安装的，安装时会出现错误，

3、上午有重新进行了打包，具体的操作内容可参考此文档：[https://bugcat.top/2021/09/23/%E5%85%B6%E4%BB%96/%E4%BD%BF%E7%94%A8Github%20Action%E5%AE%9E%E7%8E%B0Android%E8%87%AA%E5%8A%A8%E6%89%93%E5%8C%85/](url)

4、然后我重新在本地打包，上传完成后，发现写好了yml文件以后，需要我去配什么密钥之内的，很麻烦，我就通过更换了上传传路径跳过了在yml文件中签名这个步骤，当然，他可能不对，，，所以大家谨慎使用
先看我的yml文件代码
```yml
name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew clean assembleRelease --stacktrace

    - name: Upload android apk
      uses: actions/upload-artifact@v2
      with:
        name: Release App
        path: app/release/app-release.apk
  
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: newtag4
        release_name: Release Automatic
        body: |
          Changes in this Release
            - First Change
            - Second Change
            - Automatic
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: app/release/app-release.apk
        asset_name: app-release.apk
        asset_content_type: application/zip
```
在这个地方，由于我重新打包的文件是在一个新的路径，且我本地重新打包以后，是可以安装的，所以我在yml文件中替换
了部分代码，然后再次action，就可以安装了

![1693218026609](https://github.com/XJQ124/-/assets/139094062/6179f9d7-411c-4949-9ef3-27f0a1572536)
当然，这个方法好像还是有点问题，我估计还会再改

### 导航：
文档链接：[https://developer.android.google.cn/guide/navigation?hl=zh-cn](url)
1、今天就是学习了解了一些这个，没有看多少，简单之前的RecyclerView试了试
感觉Navigation 组件的主要作用是简化应用程序内不同页面之间的导航流程管理，明天再继续学习，，，
