### ISSUE TITLE
完成gihub的自动发布  

### ISSUE THREAD

**Issue by XJQ124** [XJQ124/-#2]
### 任务：github自动打包

#### 1、在android studio中创建一个新的 JKS 格式 keystore 文件，这个可以使用 Java 的 keytool 工具来创建。

```
keytool -genkey -v -keystore xjq.jks -alias muisc -storepass 123456 -keypass 123456 -keyalg RSA -keysize 2048 -validity 36500
```
这是是创建了一个xjq.jks的文件，命名为muisc

#### 2、本地环境进行签名打包

可参考链接：[https://developer.android.com/studio/publish/app-signing?hl=zh-cn](url)
其实上面也可以不参考这种方式，文档中有ide打包的方式。后面的步骤跟着文档走就行

#### 3、上传github，实现发布

```yml
name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew clean assembleRelease --stacktrace

    - name: Upload android apk
      uses: actions/upload-artifact@v2
      with:
        name: Release App
        path: app/build/outputs/apk/release/app-release.apk
  
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: newtag6
        release_name: Release Automatic
        body: |
          Changes in this Release
            - First Change
            - Second Change
            - Automatic
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: app/build/outputs/apk/release/app-release.apk
        asset_name: app-release.apk
        asset_content_type: application/zip

```
至此，才算是完成了真正的打包，我昨天那个算是取巧了，老师说那个只是debug的包，现在这个才是正常的

#### 遗留问题：
1、其实不需要在本地完成打包也是可以实现发布的，可以在GitHub上完成，这个我后面会再研究研究
2、目前这个每次发布需要我手动更改tag名字，我后面自己抽空把这个地方改掉
每天会继续安卓导航的学习
